services:
  app:
    image: vacancy-backend
    build:
      context: "."
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ".env"
    environment:
      ENV_MODE: "prod"
      REDIS_PORT: "6379"
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
    restart: always
    volumes:
      - ./src/redis/redis_data:/data
