services:
  app:
    image: vacancy-backend
    build:
      context: "."
      dockerfile: ./Dockerfile
    container_name: backend
    restart: always
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ".env"
    environment:
      ENV_MODE: "prod"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - redis

  worker1:
    image: vacancy-backend-worker
    build:
      context: "."
      dockerfile: ./worker.Dockerfile
    restart: always
    container_name: worker1
    command: ["python3", "-m", "src.redis.worker"]
    env_file:
      - ".env"
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
    restart: always
    volumes:
      - ./src/redis/redis_data:/data
