services:
  app:
    build: .
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      COOKIES: /run/secrets/lin_cookies
    secrets:
      - lin_cookies

secrets:
  lin_cookies:
    file: ./linkedin_cookies.json
